version: '3.8'

services:
  service1:
    build: ./service1
    ports:
      - "8081:8080"
    restart: always

  service2:
    build: ./service2
    ports:
      - "8082:8080"
    restart: always

  service3:
    build: ./service3
    ports:
      - "8083:8080"
    restart: always